#!/usr/bin/env python3
#
# pnp_icons.py
#
# Draw the Pick and Place status screen icons and export them as
# 64x64 4-bit greyscale C++ arrays for TFT_COLOR_UI.
#
# Pixel values: 8 = background ... 15 = icon color (see TFT_Queue::add_image)
#
# Usage: pnp_icons.py OUTPUT_DIR [PREVIEW.png]
#

import sys, math, os
from PIL import Image, ImageDraw

SIZE = 64
SS = 8              # Supersampling factor
C = SIZE * SS

HEADER = """/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2026 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// Generated by buildroot/share/scripts/pnp_icons.py

#include "../../../inc/MarlinConfig.h"

#if ALL(HAS_GRAPHICAL_TFT, PNP_STATUS_SCREEN)

#include "../tft_image.h"

"""

def canvas():
    img = Image.new('L', (C, C), 0)
    return img, ImageDraw.Draw(img)

def s(v): return int(round(v * SS))

def line(d, x0, y0, x1, y1, w):
    d.line([s(x0), s(y0), s(x1), s(y1)], fill=255, width=s(w))

def circle(d, cx, cy, r, w=0):
    box = [s(cx - r), s(cy - r), s(cx + r), s(cy + r)]
    if w: d.ellipse(box, outline=255, width=s(w))
    else: d.ellipse(box, fill=255)

def poly(d, pts):
    d.polygon([(s(x), s(y)) for x, y in pts], fill=255)

def pump():
    # Pipes, round body and a triangle showing the flow direction
    img, d = canvas()
    line(d, 4, 32, 14, 32, 5)
    line(d, 50, 32, 60, 32, 5)
    circle(d, 32, 32, 19, 4)
    poly(d, [(24, 21), (24, 43), (45, 32)])
    return img

def valve():
    # Two triangles tip to tip, with a stem and an actuator on top
    img, d = canvas()
    line(d, 4, 40, 12, 40, 5)
    line(d, 52, 40, 60, 40, 5)
    poly(d, [(12, 27), (12, 53), (32, 40)])
    poly(d, [(52, 27), (52, 53), (32, 40)])
    line(d, 32, 40, 32, 20, 4)
    d.rounded_rectangle([s(21), s(9), s(43), s(21)], radius=s(3), fill=255)
    return img

def light():
    # Bulb with a base and rays
    img, d = canvas()
    circle(d, 32, 28, 13)
    d.rounded_rectangle([s(26), s(38), s(38), s(47)], radius=s(1), fill=255)
    line(d, 27, 51, 37, 51, 3)
    line(d, 29, 56, 35, 56, 3)
    for a in (-180, -135, -90, -45, 0):
        r0, r1 = 18, 25
        ca, sa = math.cos(math.radians(a)), math.sin(math.radians(a))
        line(d, 32 + ca * r0, 28 + sa * r0, 32 + ca * r1, 28 + sa * r1, 3.5)
    return img

def to_indexes(img):
    small = img.resize((SIZE, SIZE), Image.LANCZOS)
    return [8 + (min(max(v, 0), 255) * 7 + 127) // 255 for v in small.getdata()]

def write_cpp(path, name, idx):
    data = [(idx[i] << 4) | idx[i + 1] for i in range(0, len(idx), 2)]
    per_row = SIZE // 2
    with open(path, 'w', newline='\n') as f:
        f.write(HEADER)
        f.write("const uint8_t %s_64x64x4[%d] = {\n" % (name.lower(), len(data)))
        for r in range(0, len(data), per_row):
            f.write("  " + ", ".join("0x%02X" % b for b in data[r:r + per_row]) + ",\n")
        f.write("};\n\n")
        f.write("const tImage %s_64x64x4 = { (void *)%s_64x64x4, 64, 64, GREYSCALE4 };\n\n" % (name, name.lower()))
        f.write("#endif // HAS_GRAPHICAL_TFT && PNP_STATUS_SCREEN\n")

ICONS = (('Pnp_Pump', pump), ('Pnp_Valve', valve), ('Pnp_Light', light))

if len(sys.argv) < 2:
    print("Usage: pnp_icons.py OUTPUT_DIR [PREVIEW.png]")
    sys.exit(1)

out_dir = sys.argv[1]
preview = Image.new('L', (SIZE * len(ICONS) * 4, SIZE * 4), 0)

for n, (name, draw) in enumerate(ICONS):
    idx = to_indexes(draw())
    write_cpp(os.path.join(out_dir, name.lower() + '_64x64x4.cpp'), name, idx)
    shown = Image.new('L', (SIZE, SIZE))
    shown.putdata([(v - 8) * 255 // 7 for v in idx])
    preview.paste(shown.resize((SIZE * 4, SIZE * 4), Image.NEAREST), (n * SIZE * 4, 0))
    print("Wrote", name)

if len(sys.argv) > 2: preview.save(sys.argv[2])
